### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by Mascot-N** [etherfun/MHYNotRelease#1]
我看到插件商店上新了就随手试了一下，怎么说呢，现在至少有两个问题
1，歌曲名字前的封面显示有问题（不清楚和其他插件有没有关系）
2，播放的时候去其他歌手主页同样会显示未上架歌曲
![image](https://github.com/user-attachments/assets/c127fe88-4e9f-4bd1-93a3-0968e8445446)

**Comment by etherfun** [comment]
第一个可能是[ArtistAllSongs](https://github.com/thy646742/ArtistAllSongs)的混合bug(基本ui和判断逻辑是用了他的) 但是我这没复现 不确定是不是
第二个现在已经修了 没写其他歌手的歌手页的清除逻辑 等下一个版本发布

**Comment by xiaoxuan010** [comment]
同样出现问题一，使用的是自带的主题

![image](https://github.com/user-attachments/assets/6f4d8539-d4fd-403c-a9e8-fdab376de245)

**Comment by etherfun** [comment]
已经定位到问题一的bug了是[ArtistAllSongs](https://github.com/thy646742/ArtistAllSongs)这个插件提供了封面图的css 但是没安装这个插件的就会出问题 准备修复

**Comment by etherfun** [comment]
已提交1.2.1版本  等待插件仓库同步
